import os
from datetime import datetime
import json

class EvidenceGenerator:
    def __init__(self, evidence_dir="evidence_locker"):
        self.evidence_dir = evidence_dir
        if not os.path.exists(self.evidence_dir):
            os.makedirs(self.evidence_dir)

    def generate_report(self, call_data):
        """
        Generates a forensic HTML report for the call.
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"VocalGuard_Forensic_Report_{timestamp}.html"
        filepath = os.path.join(self.evidence_dir, filename)

        risk_score = call_data.get('risk_score', 0)
        threats = call_data.get('detected_threats', [])
        transcript = call_data.get('transcript', "No transcript available.")
        
        # Determine Threat Level Color
        header_color = "#10b981" # Green
        if risk_score > 50: header_color = "#f59e0b" # Yellow
        if risk_score > 80: header_color = "#ef4444" # Red

        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>VocalGuard Forensic Report</title>
            <style>
                body {{ font-family: 'Courier New', Courier, monospace; background: #f0f2f5; padding: 40px; }}
                .container {{ max-width: 800px; margin: 0 auto; background: white; padding: 40px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); border-radius: 8px; }}
                .header {{ background: {header_color}; color: white; padding: 20px; text-align: center; border-radius: 4px; margin-bottom: 30px; }}
                .meta-table {{ width: 100%; border-collapse: collapse; margin-bottom: 20px; }}
                .meta-table td {{ padding: 10px; border-bottom: 1px solid #eee; }}
                .label {{ font-weight: bold; color: #555; }}
                .risk-score {{ font-size: 48px; font-weight: bold; text-align: center; margin: 20px 0; }}
                .threat-tag {{ display: inline-block; background: #fee2e2; color: #991b1b; padding: 4px 8px; border-radius: 4px; font-size: 12px; margin-right: 5px; font-weight: bold; }}
                .transcript-box {{ background: #f8fafc; border-left: 4px solid #334155; padding: 15px; margin-top: 20px; white-space: pre-wrap; }}
                .footer {{ margin-top: 40px; text-align: center; color: #94a3b8; font-size: 12px; border-top: 1px solid #eee; padding-top: 20px; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>FORENSIC EVIDENCE REPORT</h1>
                    <p>Generated by VocalGuard AI Defense System</p>
                </div>

                <div class="risk-score" style="color: {header_color}">
                    RISK SCORE: {risk_score}/100
                </div>

                <table class="meta-table">
                    <tr>
                        <td class="label">DATE/TIME:</td>
                        <td>{datetime.now().strftime("%B %d, %Y - %H:%M:%S")}</td>
                    </tr>
                    <tr>
                        <td class="label">CALLER ID:</td>
                        <td>{call_data.get('caller_number', 'Unknown')}</td>
                    </tr>
                    <tr>
                        <td class="label">DETECTED INTENTS:</td>
                        <td>
                            {' '.join([f'<span class="threat-tag">{t}</span>' for t in threats]) if threats else "None Detected"}
                        </td>
                    </tr>
                </table>

                <h3>📝 Transcript Evidence</h3>
                <div class="transcript-box">
{transcript}
                </div>

                <h3>🔒 Security Analysis</h3>
                <p>This call was analyzed in real-time. The AI detected specific patterns indicating potential fraud activity. This document serves as automated evidence.</p>

                <div class="footer">
                    VocalGuard AI • Anti-Scam Protection System • ID: {timestamp}
                </div>
            </div>
        </body>
        </html>
        """

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return filepath
